### PR TITLE
Add camera resolution customisation

### PR DESCRIPTION
**Pull request by Shadow149**
Add the ability to choose specific camera resolutions for every camera. Can choose from `[32, 40, 64, 128, 256]` for both width and height, keeping the old default resolution of `32x40`.

### CODE REVIEW

**Comment by rrrobo** [comment]
htps://eca8983a.erebus-robot-customisation.pages.dev

**Comment by rrrobo** [comment]
https://eca8983a.erebus-robot-customisation.pages.dev

**Comment by rrrobo** [comment]
LGTM

**Comment by rrrobo** [comment]
Can we change the cost depending on the camera resolution? If the team uses 256 x 256 cam, it'll cost more than 30 x 30.

**Comment by Shadow149** [comment]
Different resolutions should have differing costs.
For both width and height, costs are: 32px: 0, 40px: 0, 64px: 100, 128px: 200, 255: 300.

Also added gizmos for moving and rotating sensors - this makes moving components much easier.

**Pull request merged**
